#!/bin/bash

echo Hello world!
sudo mysql --database number_plate < customers.sql
sudo mysql --database number_plate < entries.sql
virtualenv --python=/usr/bin/python3.7 .
source bin/activate
pip install -r requirements.txt
